name: Run Python Script

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'  # This runs the workflow every Sunday at midnight UTC.
  workflow_dispatch:  # Allows manual triggering of the workflow.

permissions:
  contents: write  # Grants write permission to commit and push changes

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Use the built-in token to push changes

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install requests

    - name: Run the script
      run: python ./update_altstore_json.py  # Correct filename

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add altsore.json
        git commit -m "Update altsore.json with the latest releases" || echo "No changes to commit"
        git push origin HEAD:master  # Push changes back to the repository
