name: Update Apps JSON

on:
  push:
    branches:
      - master  # Adjust to your default branch if different
  schedule:
    - cron: '0 0 * * 0'  # This runs the workflow every Sunday at midnight UTC.
  workflow_dispatch:  # Allows manual triggering of the workflow.

jobs:
  update-apps-json:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests PyGithub  # Install requests and PyGithub

    - name: Run the script
      run: python ./update_apps_json.py

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Use your secret here
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add apps.json
        git commit -m "Update apps.json with the latest releases" || echo "No changes to commit"
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/Raghav1729/altstore.git HEAD:master

